class ZipCode < ActiveRecord::Base
  is_indexed :fields => [{:field => :zip}, 
                         {:field => :city}, 
                         {:field => :state, :sortable => true},
                         {:field => :state_des}]
                         
  STATE_CODE = [ "AK",
                 "AL",
                 "AR",
                 "AZ",
                 "CA",
                 "CO",
                 "CT",
                 "DC",
                 "DE",
                 "FL",
                 "GA",
                 "HI",
                 "IA",
                 "ID",
                 "IL",
                 "IN",
                 "KS",
                 "KY",
                 "LA",
                 "MA",
                 "MD",
                 "ME",
                 "MI",
                 "MN",
                 "MO",
                 "MS",
                 "MT",
                 "NC",
                 "ND",
                 "NE",
                 "NH",
                 "NJ",
                 "NM",
                 "NV",
                 "NY",
                 "OH",
                 "OK",
                 "OR",
                 "PA",
                 "RI",
                 "SC",
                 "SD",
                 "TN",
                 "TX",
                 "UT",
                 "VA",
                 "VT",
                 "WA",
                 "WI",
                 "WV",
                 "WY"
              ]
  
  STATE_DES = [  "ALASKA              ",
                 "ALABAMA             ",
                 "ARKANSAS            ",
                 "ARIZONA             ",
                 "CALIFORNIA          ",
                 "COLORADO            ",
                 "CONNECTICUT         ",
                 "DISTRICT OF COLUMBIA",
                 "DELAWARE            ",
                 "FLORIDA             ",
                 "GEORGIA             ",
                 "HAWAII              ",
                 "IOWA                ",
                 "IDAHO               ",
                 "ILLINOIS            ",
                 "INDIANA             ",
                 "KANSAS              ",
                 "KENTUCKY            ",
                 "LOUISIANA           ",
                 "MASSACHUSETTS       ",
                 "MARYLAND            ",
                 "MAINE               ",
                 "MICHIGAN            ",
                 "MINNESOTA           ",
                 "MISSOURI            ",
                 "MISSISSIPPI         ",
                 "MONTANA             ",
                 "NORTH CAROLINA      ",
                 "NORTH DAKOTA        ",
                 "NEBRASKA            ",
                 "NEW HAMPSHIRE       ",
                 "NEW JERSEY          ",
                 "NEW MEXICO          ",
                 "NEVADA              ",
                 "NEW YORK            ",
                 "OHIO                ",
                 "OKLAHOMA            ",
                 "OREGON              ",
                 "PENNSYLVANIA        ",
                 "RHODE ISLAND        ",
                 "SOUTH CAROLINA      ",
                 "SOUTH DAKOTA        ",
                 "TENNESSEE           ",
                 "TEXAS               ",
                 "UTAH                ",
                 "VIRGINIA            ",
                 "VERMONT             ",
                 "WASHINGTON          ",
                 "WISCONSIN           ",
                 "WEST VIRGINIA       ",
                 "WYOMING             "
              ]
  
end
